ZIJKANT = "|"
BOVENKANT = "="
SCHERMBREEDTE = 20
HALVESCHERMBREEDTE = SCHERMBREEDTE / 2

header = str(BOVENKANT * SCHERMBREEDTE) + "\n{0:<{1}}{2:>{3}}"
print(header.format(ZIJKANT, int(HALVESCHERMBREEDTE), ZIJKANT, 10))
